---
- name: docker_volumes directory
  ansible.builtin.file:
    path: /mnt/docker-volumes
    state: directory

- name: Mount docker_volumes
  ansible.posix.mount:
      src: truenas.home.olivando.me:/mnt/fast-storage/docker-volumes
      path: /mnt/docker-volumes
      fstype: nfs
      state: mounted
