services:
  bind9-authoritative:
    container_name: bind9-authoritative
    image: ubuntu/bind9

    environment:
      - BIND9_USER=root
      - TZ=Europe/London

    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    # network_mode: host

    volumes:
      - /etc/bind/authoritative:/etc/bind:ro
      - /var/bind/authoritative:/var/bind

    restart: unless-stopped