services:
  bind9-resolver:
    container_name: bind9-resolver
    image: ubuntu/bind9

    environment:
      - BIND9_USER=root
      - TZ=Europe/London

    network_mode: host

    volumes:
      - /mnt/docker_volumes/bind9-resolver/config:/etc/bind:ro
      - /var/bind/resolver:/var/bind

    restart: unless-stopped