services:
  ts-authkey-test:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale-homelab
    environment:
      - TS_AUTHKEY=<one time auth key from tailscale admin page>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-routes=192.168.1.0/24
    volumes:
      - tailscale-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - net_raw
    network_mode: host
    restart: unless-stopped

volumes:
  tailscale-state:
